pull_request_rules:
  - name: automatic merge for PyUp pull requests
    conditions:
      - author=pyup-bot
      - label!=work-in-progress
    actions:
      merge:
        method: merge
  - name: automatic merge when PR is approved
    conditions:
      - "#approved-reviews-by>=2"
    actions:
      merge:
        method: merge
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
