language: python
python:
  - 3.10-dev
  - 3.9
  - 3.8
  - 3.7
  - 3.6
install:
  - pip install -U setuptools && pip install tox tox-travis coveralls
script:
  - tox < testing.txt
after_success:
  - coveralls
notifications:
    email: false
